openapi: 3.0.0

info:
  title: Analytics
  description: API for handling analytics data.
  version: 0.1.0

tags:
  - name: Analytics
    description: Endpoints related to analytics data

paths:
  /initiate-analytics-dashboard:
    get:
      tags:
        - Analytics
      operationId: initiateAnalyticsDashboard
      summary: Initiate necessary fields in dashboard.
      description: >
        Returns the filters and other fields for dashboard functionalities.
      responses:
        '200':
          description: A JSON array of analytics data
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  description: List of departments that are available to be used as filters
                  example: "DepartmentBean of Public Safety - Police"

  /get-timeline-data:
    get:
      tags:
        - Analytics
      operationId: getTimelineData
      summary: Retrieve timeline data for the dashboard.
      description: >
        Returns the filters and other fields for dashboard functionalities.
      parameters:
        - name: period
          in: query
          description: End date for the timeline data
          schema:
            type: string
            example: "[Quarterly, Yearly, Monthly]"
        - name: year
          in: query
          description: Start date for the timeline data
          schema:
            type: integer
            format: date
            example: "2012"
        - name: departmentNameKey
          in: query
          description: DepartmentBean to filter the timeline data
          schema:
            type: string
            example: "Finance"
      responses:
        '200':
          description: A JSON array of timeline items
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TimelineResponseModel'

  /get-top-n-fund-description-breakdown:
    post:
      tags:
        - Analytics
      operationId: getTopNFundDescriptionBreakdown
      summary: TO WRITE LATER
      description: >
        TO WRITE LATER.
      requestBody:
        description: A JSON array of timeline items
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/AnalyticsEnquiryModel'
      responses:
        '200':
          description: A JSON array of timeline items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TimelineItem' # this one have to modify, discuss together tomorrow

  /get-cumulative-revenue-and-expenses:
    post:
      tags:
        - Analytics
      operationId: getCumulativeRevenueAndExpenses
      summary: TO WRITE LATER.
      description: >
        WRITE LATER.
      requestBody:
        description: A JSON array of timeline items
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/AnalyticsEnquiryModel'
      responses:
        '200':
          description: A JSON array of timeline items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TimelineItem' # this one have to modify, discuss together tomorrow

  /get-department-revenue-and-expenses-breakdown:
    post:
      tags:
        - Analytics
      operationId: getDepartmentRevenueAndExpensesBreakdown
      summary: TO WRITE LATER.
      description: >
        WRITE LATER.
      requestBody:
        description: A JSON array of timeline items
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/AnalyticsEnquiryModel'
      responses:
        '200':
          description: A JSON array of timeline items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TimelineItem' # this one have to modify, discuss together tomorrow

  /get-fund-description-revenue-and-expenses-breakdown:
    post:
      tags:
        - Analytics
      operationId: getFundDescriptionRevenueAndExpensesBreakdown
      summary: TO WRITE LATER.
      description: >
        WRITE LATER.
      requestBody:
        description: A JSON array of timeline items
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/AnalyticsEnquiryModel'
      responses:
        '200':
          description: A JSON array of timeline items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TimelineItem' # this one have to modify, discuss together tomorrow

components:
  schemas:
    AnalyticsEnquiryModel:
      type: object
      description: Model used to enquire/request for data based on defined filters and fields
      properties:
        topNRanks:
          type: number
          description: The top N ranks to return
          example: "5"
        dateFrom:
          type: string
          format: date
          description: Starting date of filter
          example: "2024-08-10T14:48:00Z"
        dateTo:
          type: string
          format: date
          description: Ending date of filter
          example: "2024-08-30T14:48:00Z"
        department:
          type: string
          description: Variable used for filtering based on departments
          example: "Police DepartmentBean"

    TimelineResponseModel:
      type: object
      description: Response body with all data related to timeline
      properties:
        expensesTimeline:
          type: array
          items:
            $ref: '#/components/schemas/TimelineItem'
          description: An array of timeline items related to expenses
        revenueTimeline:
          type: array
          items:
            $ref: '#/components/schemas/TimelineItem'
          description: An array of timeline items related to revenue
        surplusDeficitTimeline:
          type: array
          items:
            $ref: '#/components/schemas/TimelineItem'
          description: An array of timeline items related to surplus or deficit

    TimelineItem:
      type: object
      description: Used to display the time series line chart for analytics
      properties:
        ledgerDescription:
          type: string
          description: A label for the timeline item whether this is a revenue or an expenses
          example: "[Revenue, Expenses, SurplusDeficit]"
        period:
          type: string
          description: The x-value used for display to represent the timestamp
          example: "[2012, ..., 2020] OR [January, ..., December] OR [1, 2, ..., 31]"
        amount:
          type: number
          description: The y-value representing the amount of revenue or expenses or surplusDeficit (%)
          example: "373000"
