openapi: 3.0.0

info:
  title: Analytics
  description: API for handling analytics data.
  version: 0.1.0

tags:
  - name: Analytics
    description: Endpoints related to analytics data

paths:
  /initiate-analytics-dashboard:
    get:
      tags:
        - Analytics
      operationId: initiateAnalyticsDashboard
      summary: Initiate necessary fields in dashboard.
      description: >
        Returns the filters and other fields for dashboard functionalities.
      responses:
        '200':
          description: A JSON array of department names (for display) and keys (for filtering)
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  additionalProperties:
                    type: string
                  description: A map where the key is the department name and the value is the department name key
                  example: >
                    Mayor's Office: MAYORS_OFFICE
                    Innovation and Performance: INNOVATION_AND_PERFORMANCE
                    Human Relations Commission: HUMAN_RELATIONS_COMMISSION
                    Controller's Office: CONTROLLERS_OFFICE

  /get-timeline-data:
    get:
      tags:
        - Analytics
      operationId: getTimelineData
      summary: Retrieve timeline data for the dashboard.
      description: >
        Returns the filters and other fields for dashboard functionalities.
      parameters:
        - name: period
          in: query
          description: End date for the timeline data
          schema:
            type: string
            example: "[Quarterly, Yearly, Monthly]"
        - name: year
          in: query
          description: Start date for the timeline data
          schema:
            type: integer
            format: date
            example: "2012"
        - name: departmentNameKey
          in: query
          description: DepartmentBean to filter the timeline data
          schema:
            type: string
            example: "Finance"
      responses:
        '200':
          description: A JSON array of timeline items
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TimelineResponseModel'

  /get-expenses-breakdown:
    get:
      tags:
        - Analytics
      operationId: getExpensesBreakdown
      summary: Get the breakdown of expenses
      description: >
        Get the breakdown of expenses according to year and departments
      parameters:
        - name: year
          in: query
          description: Field to filter the breakdown of expenses by year
          schema:
            type: integer
            format: date
            example: "2012"
        - name: departmentNameKey
          in: query
          description: Department name key to filter the breakdown of expenses
          schema:
            type: string
            example: "Finance"
      responses:
        '200':
          description: A JSON array of department names (for display) and keys (for filtering)
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  additionalProperties:
                    type: number
                  description: A map where the key is the department name and the value is the expense amount
                  example: >
                    Project Fund 2018 Bond: 32.45,
                    Project Fund 2019 Bond: 43.21,
                    Project Fund 2020 Bond: 21.67

  /get-revenue-and-expenses-breakdown:
    get:
      tags:
        - Analytics
      operationId: getRevenueAndExpensesBreakdown
      summary: Get the breakdown of revenue and expenses
      description: >
        Get the breakdown of revenue along with expenses according to year and departments
      parameters:
        - name: year
          in: query
          description: Field to filter revenue and expenses by year
          schema:
            type: integer
            format: date
            example: "2012"
        - name: departmentNameKey
          in: query
          description: Department name key to filter the breakdown of revenue and expenses
          schema:
            type: string
            example: "Finance"
      responses:
        '200':
          description: A JSON array of department names (for display) and keys (for filtering)
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  additionalProperties:
                    type: number
                  description: A map where the key is the department name and the value is the expense amount
                  example: >
                    Revenue: 35.31,
                    Expenses: 64.69

  /get-financial-table-data:
    get:
      tags:
        - Analytics
      operationId: getFinancialTableData
      summary: Used to populate the data for the financial table
      description: >
        This API is used to populate the data for the financial table based on the year and the department selected
      parameters:
        - name: year
          in: query
          description: Field to filter financial table data by year
          schema:
            type: integer
            format: date
            example: "2012"
        - name: departmentNameKey
          in: query
          description: Department name key to filter the financial table data
          schema:
            type: string
            example: "Finance"
      responses:
        '200':
          description: A JSON array of Financial Table Items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FinancialTableItem'

components:
  schemas:
    FinancialTableItem:
      type: object
      description: Model that contains the financial table data based that could be filtered by year and departmentNameKey
      properties:
        description:
          type: string
          description: > 
            The description of the financial data table. It could be the department_name OR 
            the fund_description (filtered by departmentNameKey)
          example: "[City Clerk, Department of Public Safety - Police, Drug Abuse Resistance Education Trust Fund, Code Trust Fund]"
        revenue:
          type: number
          description: Reflects the revenue that is grouped by the department OR fund_description
          example: "37331000"
        expenses:
          type: number
          description: Reflects the expenses that is grouped by the department OR fund_description
          example: "500323140"

    TimelineResponseModel:
      type: object
      description: Response body with all data related to timeline
      properties:
        expensesTimeline:
          type: array
          items:
            $ref: '#/components/schemas/TimelineItem'
          description: An array of timeline items related to expenses
        revenueTimeline:
          type: array
          items:
            $ref: '#/components/schemas/TimelineItem'
          description: An array of timeline items related to revenue
        surplusDeficitTimeline:
          type: array
          items:
            $ref: '#/components/schemas/TimelineItem'
          description: An array of timeline items related to surplus or deficit

    TimelineItem:
      type: object
      description: Used to display the time series line chart for analytics
      properties:
        ledgerDescription:
          type: string
          description: A label for the timeline item whether this is a revenue or an expenses
          example: "[Revenue, Expenses, SurplusDeficit]"
        period:
          type: string
          description: The x-value used for display to represent the timestamp
          example: "[2012, ..., 2020] OR [January, ..., December] OR [1, 2, ..., 31]"
        amount:
          type: number
          description: The y-value representing the amount of revenue or expenses or surplusDeficit (%)
          example: "373000"